#include <TROOT.h>
#include <TFile.h>
#include <TH1D.h>
#include <TH2.h>
#include <THStack.h>
#include <TGraph.h>
#include <TMultiGraph.h>
#include <TCanvas.h>
#include <TMath.h>
#include <TF1.h>
#include <TLine.h>
#include <TLegend.h>
#include <TProfile.h>
#include <TLatex.h>
#include <TAxis.h>
#include <TString.h>
#include <TStyle.h>

#include <iostream>
#include <fstream>
#include <iomanip>
#include <stdlib.h>
#include <string>
#include "plots.C"
#include "drawACP.C"
#include "stack.C"
#include "draw2D.C"
using namespace std;
void resultsDATAMC(TFile* f, string output=".", bool unblind=false ){

    //drawObservable( f, "MC__Evt_O7Asym",      output, "O_{7}^{e+#mu}", 	"Combined", 0.05, 0);
    //drawObservable( f, "MC__Evt_O2Asym",      output, "O_{2}^{e+#mu}", 	"Combined", 0.05, 1);
    //drawObservable( f, "MC__Evt_O7Asym_Mu",   output, "O_{7}^{#mu}", 	"Muon", 	0.05, 0);
    //drawObservable( f, "MC__Evt_O2Asym_Mu",   output, "O_{2}^{#mu}", 	"Muon", 	0.05, 1);
    //drawObservable( f, "MC__Evt_O7Asym_El",   output, "O_{7}^{e}", 		"Electron", 0.05, 0);
    //drawObservable( f, "MC__Evt_O2Asym_El",   output, "O_{2}^{e}", 		"Electron", 0.05, 1);

    //drawObservableDist( f, output, "MC__Evt_O7", 	"O_{7}/M_{top}^{3}", "LepJets", 1);
    //drawObservableDist( f, output, "MC__Evt_O2", 	"O_{2}/M_{top}^{3}", "LepJets", 1);
    drawACP( f, 1, "", "MC__Evt",    "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "MC__Evt",    "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "MC__Evt",    "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "MC__Evt",    "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "BkgMC__Evt", "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "BkgMC__Evt", "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "BkgMC__Evt", "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "BkgMC__Evt", "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__Evt", "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__Evt", "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__Evt", "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__Evt", "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "TTJets__Evt", "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "TTJets__Evt", "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "TTJets__Evt", "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "TTJets__Evt", "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__Evt",     "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__Evt",     "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__Evt",     "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__Evt",     "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "MC__EvtChi2",    "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "MC__EvtChi2",    "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "MC__EvtChi2",    "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "MC__EvtChi2",    "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "BkgMC__EvtChi2", "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "BkgMC__EvtChi2", "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "BkgMC__EvtChi2", "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "BkgMC__EvtChi2", "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__EvtChi2", "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__EvtChi2", "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__EvtChi2", "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__EvtChi2", "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "TTJets__EvtChi2", "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "TTJets__EvtChi2", "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "TTJets__EvtChi2", "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "TTJets__EvtChi2", "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__EvtChi2", "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__EvtChi2", "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__EvtChi2", "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__EvtChi2", "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "MC__EvtMlb",    "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "MC__EvtMlb",    "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "MC__EvtMlb",    "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "MC__EvtMlb",    "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "BkgMC__EvtMlb", "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "BkgMC__EvtMlb", "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "BkgMC__EvtMlb", "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "BkgMC__EvtMlb", "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__EvtMlb", "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__EvtMlb", "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__EvtMlb", "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "TTJets_SemiLeptMGDecays__EvtMlb", "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "TTJets__EvtMlb", "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "TTJets__EvtMlb", "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "TTJets__EvtMlb", "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "TTJets__EvtMlb", "O7", output, "A'_{CP} [%]", "O_{7}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__EvtMlb", "O2", output, "A'_{CP} [%]", "O_{2}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__EvtMlb", "O3", output, "A'_{CP} [%]", "O_{3}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__EvtMlb", "O4", output, "A'_{CP} [%]", "O_{4}");
    drawACP( f, 1, "", "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__EvtMlb", "O7", output, "A'_{CP} [%]", "O_{7}");
    if( unblind ){
        drawACP2Ch( f, 0, "", "DATA_Electron__Evt", "DATA_Muon__Evt", "O2", output, "A'_{CP} [%]", "O_{2}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__Evt", "DATA_Muon__Evt", "O3", output, "A'_{CP} [%]", "O_{3}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__Evt", "DATA_Muon__Evt", "O4", output, "A'_{CP} [%]", "O_{4}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__Evt", "DATA_Muon__Evt", "O7", output, "A'_{CP} [%]", "O_{7}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__Evt", "DATA_Muon__Evt", "Oa", output, "A'_{CP} [%]", "O_{a}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__Evt", "DATA_Muon__Evt", "Ob", output, "A'_{CP} [%]", "O_{b}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtChi2", "DATA_Muon__EvtChi2", "O2", output, "A'_{CP} [%]", "O_{2}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtChi2", "DATA_Muon__EvtChi2", "O3", output, "A'_{CP} [%]", "O_{3}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtChi2", "DATA_Muon__EvtChi2", "O4", output, "A'_{CP} [%]", "O_{4}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtChi2", "DATA_Muon__EvtChi2", "O7", output, "A'_{CP} [%]", "O_{7}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtChi2", "DATA_Muon__EvtChi2", "Oa", output, "A'_{CP} [%]", "O_{a}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtChi2", "DATA_Muon__EvtChi2", "Ob", output, "A'_{CP} [%]", "O_{b}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtMlb",  "DATA_Muon__EvtMlb",  "O2", output, "A'_{CP} [%]", "O_{2}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtMlb",  "DATA_Muon__EvtMlb",  "O3", output, "A'_{CP} [%]", "O_{3}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtMlb",  "DATA_Muon__EvtMlb",  "O4", output, "A'_{CP} [%]", "O_{4}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtMlb",  "DATA_Muon__EvtMlb",  "O7", output, "A'_{CP} [%]", "O_{7}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtMlb",  "DATA_Muon__EvtMlb",  "Oa", output, "A'_{CP} [%]", "O_{a}", "Signal region");
        drawACP2Ch( f, 0, "", "DATA_Electron__EvtMlb",  "DATA_Muon__EvtMlb",  "Ob", output, "A'_{CP} [%]", "O_{b}", "Signal region");
        float scaleY=0.001;
        drawObservableData(f, output, "O2", "EvtMlb", "Signal region", "O_{2}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
        drawObservableData(f, output, "O3", "EvtMlb", "Signal region", "O_{3}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
        drawObservableData(f, output, "O4", "EvtMlb", "Signal region", "O_{4}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
        drawObservableData(f, output, "O7", "EvtMlb", "Signal region", "O_{7}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
        drawObservableData(f, output, "Oa", "EvtMlb", "Signal region", "O_{a}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
        drawObservableData(f, output, "Ob", "EvtMlb", "Signal region", "O_{b}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
        drawObservableData(f, output, "O2", "EvtChi2", "Signal region", "O_{2}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
        drawObservableData(f, output, "O3", "EvtChi2", "Signal region", "O_{3}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
        drawObservableData(f, output, "O4", "EvtChi2", "Signal region", "O_{4}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
        drawObservableData(f, output, "O7", "EvtChi2", "Signal region", "O_{7}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
        drawObservableData(f, output, "Oa", "EvtChi2", "Signal region", "O_{a}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
        drawObservableData(f, output, "Ob", "EvtChi2", "Signal region", "O_{b}", "Events #times 10^{3} / 0.1", scaleY, -1, 1, 1 );
    }

    //float o_min=-3, o_max=3;
    //int bin=2;
    float o_min=-1, o_max=1;
    int bin=1;
    if( unblind ){
        drawStackWithData( f, "Evt_O2",        "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O2",        "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O3",        "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O3",        "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O4",        "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O4",        "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O7",        "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O7",        "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Oa",        "O_{a}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Oa",        "O_{a}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Ob",        "O_{b}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Ob",        "O_{b}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O2_Mu",     "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O2_Mu",     "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O3_Mu",     "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O3_Mu",     "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O4_Mu",     "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O4_Mu",     "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O7_Mu",     "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O7_Mu",     "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Oa_Mu",     "O_{a}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Oa_Mu",     "O_{a}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Ob_Mu",     "O_{b}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Ob_Mu",     "O_{b}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O2_El",     "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O2_El",     "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O3_El",     "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O3_El",     "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O4_El",     "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O4_El",     "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O7_El",     "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_O7_El",     "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Oa_El",     "O_{a}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Oa_El",     "O_{a}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Ob_El",     "O_{b}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "Evt_Ob_El",     "O_{b}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O2",    "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O2",    "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O3",    "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O3",    "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O4",    "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O4",    "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O7",    "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O7",    "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Oa",    "O_{a}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Oa",    "O_{a}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Ob",    "O_{b}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Ob",    "O_{b}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O2_Mu", "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O2_Mu", "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O3_Mu", "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O3_Mu", "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O4_Mu", "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O4_Mu", "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O7_Mu", "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O7_Mu", "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Oa_Mu", "O_{a}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Oa_Mu", "O_{a}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Ob_Mu", "O_{b}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Ob_Mu", "O_{b}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O2_El", "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O2_El", "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O3_El", "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O3_El", "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O4_El", "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O4_El", "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O7_El", "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_O7_El", "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Oa_El", "O_{a}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Oa_El", "O_{a}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Ob_El", "O_{b}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtChi2_Ob_El", "O_{b}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O2",    "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O2",    "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O3",    "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O3",    "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O4",    "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O4",    "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O7",    "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O7",    "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Oa",    "O_{a}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Oa",    "O_{a}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Ob",    "O_{b}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Ob",    "O_{b}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O2_Mu", "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O2_Mu", "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O3_Mu", "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O3_Mu", "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O4_Mu", "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O4_Mu", "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O7_Mu", "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O7_Mu", "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Oa_Mu", "O_{a}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Oa_Mu", "O_{a}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Ob_Mu", "O_{b}^{#mu}/M_{top}^{3}",   "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Ob_Mu", "O_{b}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O2_El", "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O2_El", "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O3_El", "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O3_El", "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O4_El", "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O4_El", "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O7_El", "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_O7_El", "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Oa_El", "O_{a}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Oa_El", "O_{a}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Ob_El", "O_{b}^{e}/M_{top}^{3}",     "Events", output, bin, false ,0, o_min, o_max);
        drawStackWithData( f, "EvtMlb_Ob_El", "O_{b}^{e}/M_{top}^{3}",     "Events", output, bin, true  ,0, o_min, o_max);
    }else{
        drawStack( f, "Evt_O2",    "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O2",    "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "Evt_O3",    "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O3",    "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "Evt_O4",    "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O4",    "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "Evt_O7",    "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O7",    "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "Evt_O2_Mu", "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O2_Mu", "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "Evt_O3_Mu", "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O3_Mu", "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "Evt_O4_Mu", "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O4_Mu", "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "Evt_O7_Mu", "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O7_Mu", "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "Evt_O2_El", "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O2_El", "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "Evt_O3_El", "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O3_El", "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "Evt_O4_El", "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O4_El", "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "Evt_O7_El", "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "Evt_O7_El", "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O2",    "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O2",    "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O3",    "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O3",    "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O4",    "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O4",    "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O7",    "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O7",    "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O2_Mu", "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O2_Mu", "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O3_Mu", "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O3_Mu", "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O4_Mu", "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O4_Mu", "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O7_Mu", "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O7_Mu", "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O2_El", "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O2_El", "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O3_El", "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O3_El", "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O4_El", "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O4_El", "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtChi2_O7_El", "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtChi2_O7_El", "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O2",    "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O2",    "O_{2}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O3",    "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O3",    "O_{3}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O4",    "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O4",    "O_{4}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O7",    "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O7",    "O_{7}^{e+#mu}/M_{top}^{3}", "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O2_Mu", "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O2_Mu", "O_{2}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O3_Mu", "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O3_Mu", "O_{3}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O4_Mu", "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O4_Mu", "O_{4}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O7_Mu", "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O7_Mu", "O_{7}^{#mu}/M_{top}^{3}",   "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O2_El", "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O2_El", "O_{2}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O3_El", "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O3_El", "O_{3}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O4_El", "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O4_El", "O_{4}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
        drawStack( f, "EvtMlb_O7_El", "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, false , o_min, o_max);
        drawStack( f, "EvtMlb_O7_El", "O_{7}^{e}/M_{top}^{3}",     "Events", output, bin, true  , o_min, o_max);
    }
    // Linear
    drawStackWithData(f, "EvtNJet_NVertexNoWrt",     "N(selected vtx)",               "PDF", output, 1,0,1 );  
    drawStackWithData(f, "EvtNJet_NVertex",          "N(selected vtx)",               "PDF", output, 1,0,1 );  
    drawStackWithData(f, "Evt_NSelJets_El",          "N(selected jets), e-ch.",                             "Events", output, 1 );  
    drawStackWithData(f, "Evt_NSelJets_Mu",          "N(selected jets), #mu-ch.",                           "Events", output, 1 );  
    drawStackWithData(f, "Evt_NBJets_El",            "N(CSVM b-tagged jets), e-ch.",                        "Events", output, 1 );  
    drawStackWithData(f, "Evt_NBJets_Mu",            "N(CSVM b-tagged jets), #mu-ch.",                      "Events", output, 1 );  
    drawStackWithData(f, "Evt_HardJet_Pt_El",        "p_{T}(leading jet), e-ch. [GeV]",                           "Events", output, 10 );  
    drawStackWithData(f, "Evt_HardJet_Pt_Mu",        "p_{T}(leading jet), #mu-ch. [GeV]",                         "Events", output, 10 ); 
    drawStackWithData(f, "Evt_HardJet_E_El",         "Energy(leading jet), e-ch. [GeV]",                          "Events", output, 10 );  
    drawStackWithData(f, "Evt_HardJet_E_Mu",         "Energy(leading jet), #mu-ch. [GeV]",                        "Events", output, 10 ); 
    drawStackWithData(f, "Evt_HardJet_Eta_El",       "#eta(leading jet), e-ch.",                            "Events", output, 2  );  
    drawStackWithData(f, "Evt_HardJet_Eta_Mu",       "#eta(leading jet), #mu-ch.",                          "Events", output, 2  ); 
    drawStackWithData(f, "Evt_HardNonBJet1_Pt_El",   "p_{T}(leading non b-jet), e-ch. [GeV]",                     "Events", output, 10 );  
    drawStackWithData(f, "Evt_HardNonBJet1_Pt_Mu",   "p_{T}(leading non b-jet), #mu-ch. [GeV]",                   "Events", output, 10 ); 
    drawStackWithData(f, "Evt_HardNonBJet1_E_El",    "Energy(leading non b-jet), e-ch. [GeV]",                    "Events", output, 10 );  
    drawStackWithData(f, "Evt_HardNonBJet1_E_Mu",    "Energy(leading non b-jet), #mu-ch. [GeV]",                  "Events", output, 10 ); 
    drawStackWithData(f, "Evt_HardNonBJet1_Eta_El",  "#eta(leading non b-jet), e-ch.",                      "Events", output, 2  );  
    drawStackWithData(f, "Evt_HardNonBJet1_Eta_Mu",  "#eta(leading non b-jet), #mu-ch.",                    "Events", output, 2  ); 
    drawStackWithData(f, "Evt_HardNonBJet2_Pt_El",   "p_{T}(second non b-jet), e-ch. [GeV]",                      "Events", output, 10 );  
    drawStackWithData(f, "Evt_HardNonBJet2_Pt_Mu",   "p_{T}(second non b-jet), #mu-ch. [GeV]",                    "Events", output, 10 ); 
    drawStackWithData(f, "Evt_HardNonBJet2_E_El",    "Energy(second non b-jet), e-ch. [GeV]",                     "Events", output, 10 );  
    drawStackWithData(f, "Evt_HardNonBJet2_E_Mu",    "Energy(second non b-jet), #mu-ch. [GeV]",                   "Events", output, 10 ); 
    drawStackWithData(f, "Evt_HardNonBJet2_Eta_El",  "#eta(second non b-jet), e-ch.",                       "Events", output, 2  );  
    drawStackWithData(f, "Evt_HardNonBJet2_Eta_Mu",  "#eta(second non b-jet), #mu-ch.",                     "Events", output, 2  ); 
    drawStackWithData(f, "Evt_TopNonBJet1_Pt_El",    "p_{T}(leading non b-jet from hadronic t), e-ch. [GeV]",     "Events", output, 10 );  
    drawStackWithData(f, "Evt_TopNonBJet1_Pt_Mu",    "p_{T}(leading non b-jet from hadronic t), #mu-ch. [GeV]",   "Events", output, 10 ); 
    drawStackWithData(f, "Evt_TopNonBJet1_E_El",     "Energy(leading non b-jet from hadronic t), e-ch. [GeV]",    "Events", output, 10 );  
    drawStackWithData(f, "Evt_TopNonBJet1_E_Mu",     "Energy(leading non b-jet from hadronic t), #mu-ch. [GeV]",  "Events", output, 10 ); 
    drawStackWithData(f, "Evt_TopNonBJet1_Eta_El",   "#eta(leading non b-jet from hadronic t), e-ch.",      "Events", output, 2  );  
    drawStackWithData(f, "Evt_TopNonBJet1_Eta_Mu",   "#eta(leading non b-jet from hadronic t), #mu-ch.",    "Events", output, 2  ); 
    drawStackWithData(f, "Evt_TopNonBJet2_Pt_El",    "p_{T}(second non b-jet from hadronic t), e-ch. [GeV]",      "Events", output, 10 );  
    drawStackWithData(f, "Evt_TopNonBJet2_Pt_Mu",    "p_{T}(second non b-jet from hadronic t), #mu-ch. [GeV]",    "Events", output, 10 ); 
    drawStackWithData(f, "Evt_TopNonBJet2_E_El",     "Energy(second non b-jet from hadronic t), e-ch. [GeV]",     "Events", output, 10 );  
    drawStackWithData(f, "Evt_TopNonBJet2_E_Mu",     "Energy(second non b-jet from hadronic t), #mu-ch.",   "Events", output, 10 ); 
    drawStackWithData(f, "Evt_TopNonBJet2_Eta_El",   "#eta(second non b-jet from hadronic t), e-ch.",       "Events", output, 2  );  
    drawStackWithData(f, "Evt_TopNonBJet2_Eta_Mu",   "#eta(second non b-jet from hadronic t), #mu-ch.",     "Events", output, 2  ); 
    drawStackWithData(f, "Evt_bJet_Pt_El",           "p_{T}(b-jet), e-ch. [GeV]",                                 "Events", output, 10 );  
    drawStackWithData(f, "Evt_bJet_Pt_Mu",           "p_{T}(b-jet), #mu-ch. [GeV]",                               "Events", output, 10 ); 
    drawStackWithData(f, "Evt_bJet_E_El",            "Energy(b-jet), e-ch. [GeV]",                                "Events", output, 10 );  
    drawStackWithData(f, "Evt_bJet_E_Mu",            "Energy(b-jet), #mu-ch. [GeV]",                              "Events", output, 10 ); 
    drawStackWithData(f, "Evt_bJet_Eta_El",          "#eta(b-jet), e-ch.",                                  "Events", output, 2  );  
    drawStackWithData(f, "Evt_bJet_Eta_Mu",          "#eta(b-jet), #mu-ch.",                                "Events", output, 2  ); 
    drawStackWithData(f, "Evt_bbarJet_Pt_El",        "p_{T}(#bar{b}-jet), e-ch. [GeV]",                           "Events", output, 10 );  
    drawStackWithData(f, "Evt_bbarJet_Pt_Mu",        "p_{T}(#bar{b}-jet), #mu-ch. [GeV]",                         "Events", output, 10 ); 
    drawStackWithData(f, "Evt_bbarJet_E_El",         "Energy(#bar{b}-jet), e-ch. [GeV]",                          "Events", output, 10 );  
    drawStackWithData(f, "Evt_bbarJet_E_Mu",         "Energy(#bar{b}-jet), #mu-ch. [GeV]",                        "Events", output, 10 ); 
    drawStackWithData(f, "Evt_bbarJet_Eta_El",       "#eta(#bar{b}-jet), e-ch.",                            "Events", output, 2  );  
    drawStackWithData(f, "Evt_bbarJet_Eta_Mu",       "#eta(#bar{b}-jet), #mu-ch.",                          "Events", output, 2  ); 
    drawStackWithData(f, "Evt_Top_Hadronic_Mass_El", "M_{jjb} [GeV]",                            "Events", output, 10 );
    drawStackWithData(f, "Evt_Top_Hadronic_Mass_Mu", "M_{jjb} [GeV]",                          "Events", output, 10 ); 
    drawStackWithData(f, "Evt_Top_Hadronic_Pt_El",   "Inv. p_{T, top}(jjb), e-ch. [GeV]",                         "Events", output, 10 );
    drawStackWithData(f, "Evt_Top_Hadronic_Pt_Mu",   "Inv. p_{T, top}(jjb), #mu-ch. [GeV]",                       "Events", output, 10 ); 
    drawStackWithData(f, "Evt_Top_Hadronic_Chi2_El", "#chi^{2}_{min}(jjb), e-ch.",                          "Events", output, 5 );
    drawStackWithData(f, "Evt_Top_Hadronic_Chi2_Mu", "#chi^{2}_{min}(jjb), #mu-ch.",                        "Events", output, 5 );
    drawStackWithData(f, "Evt_Top_Hadronic_Eta_El",  "#eta_{top}(jjb), e-ch.",                              "Events", output, 2  );
    drawStackWithData(f, "Evt_Top_Hadronic_Eta_Mu",  "#eta_{top}(jjb), #mu-ch.",                            "Events", output, 2  );
    drawStackWithData(f, "Evt_isoLep_Pt_Mu",         "p_{T}(isolated #mu) [GeV]",                                 "Events", output, 10 ); 
    drawStackWithData(f, "Evt_isoLep_Pt_El",         "p_{T}(isolated e) [GeV]",                                   "Events", output, 10 ); 
    drawStackWithData(f, "Evt_isoLep_Eta_Mu",        "#eta(isolated #mu)",                                  "Events", output, 2  ); 
    drawStackWithData(f, "Evt_isoLep_Eta_El",        "#eta(isolated e)",                                    "Events", output, 2  );
    drawStackWithData(f, "Evt_Ht_El",                "H_{T}(selected jets), e-ch. [GeV]",                         "Events", output, 20 );  
    drawStackWithData(f, "Evt_Ht_Mu",                "H_{T}(selected jets), #mu-ch. [GeV]",                       "Events", output, 20 ); 
    drawStackWithData(f, "Evt_Top_Leptonic_Mbl_El",  "M_{eb} [GeV]",                                              "Events", output, 10 );
    drawStackWithData(f, "Evt_Top_Leptonic_Mbl_Mu",  "M_{#mub} [GeV]",                                            "Events", output, 10 ); 
    // Log
    drawStackWithData(f, "Evt_NSelJets_El",          "N(selected jets), e-ch.",                             "Events", output, 1  ,1);  
    drawStackWithData(f, "Evt_NSelJets_Mu",          "N(selected jets), #mu-ch.",                           "Events", output, 1  ,1);  
    drawStackWithData(f, "Evt_NBJets_El",            "N(CSVM b-tagged jets), e-ch.",                        "Events", output, 1  ,1);  
    drawStackWithData(f, "Evt_NBJets_Mu",            "N(CSVM b-tagged jets), #mu-ch.",                      "Events", output, 1  ,1);  
    drawStackWithData(f, "Evt_HardJet_Pt_El",        "p_{T}(leading jet), e-ch. [GeV]",                           "Events", output, 10 ,1);  
    drawStackWithData(f, "Evt_HardJet_Pt_Mu",        "p_{T}(leading jet), #mu-ch. [GeV]",                         "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_HardJet_E_El",         "Energy(leading jet), e-ch. [GeV]",                          "Events", output, 10 ,1);  
    drawStackWithData(f, "Evt_HardJet_E_Mu",         "Energy(leading jet), #mu-ch. [GeV]",                        "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_HardJet_Eta_El",       "#eta(leading jet), e-ch.",                            "Events", output, 2  ,1);  
    drawStackWithData(f, "Evt_HardJet_Eta_Mu",       "#eta(leading jet), #mu-ch.",                          "Events", output, 2  ,1); 
    drawStackWithData(f, "Evt_HardNonBJet1_Pt_El",    "p_{T}(leading non b-jet), e-ch. [GeV]",                    "Events", output, 10 ,1);  
    drawStackWithData(f, "Evt_HardNonBJet1_Pt_Mu",    "p_{T}(leading non b-jet), #mu-ch. [GeV]",                  "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_HardNonBJet1_E_El",     "Energy(leading non b-jet), e-ch. [GeV]",                   "Events", output, 10 ,1);  
    drawStackWithData(f, "Evt_HardNonBJet1_E_Mu",     "Energy(leading non b-jet), #mu-ch. [GeV]",                 "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_HardNonBJet1_Eta_El",   "#eta(leading b-jet), e-ch.",                         "Events", output, 2  ,1);  
    drawStackWithData(f, "Evt_HardNonBJet1_Eta_Mu",   "#eta(leading b-jet), #mu-ch.",                       "Events", output, 2  ,1); 
    drawStackWithData(f, "Evt_HardNonBJet2_Pt_El",   "p_{T}(second non b-jet), e-ch. [GeV]",                      "Events", output, 10 ,1);  
    drawStackWithData(f, "Evt_HardNonBJet2_Pt_Mu",   "p_{T}(second non b-jet), #mu-ch. [GeV]",                    "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_HardNonBJet2_E_El",    "Energy(second non b-jet), e-ch. [GeV]",                     "Events", output, 10 ,1);  
    drawStackWithData(f, "Evt_HardNonBJet2_E_Mu",    "Energy(second non b-jet), #mu-ch. [GeV]",                   "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_HardNonBJet2_Eta_El",  "#eta(second non b-jet), e-ch.",                       "Events", output, 2  ,1);  
    drawStackWithData(f, "Evt_HardNonBJet2_Eta_Mu",  "#eta(second non b-jet), #mu-ch.",                     "Events", output, 2  ,1); 
    drawStackWithData(f, "Evt_TopNonBJet1_Pt_El",    "p_{T}(leading non b-jet from hadronic t), e-ch. [GeV]",     "Events", output, 10,1 );  
    drawStackWithData(f, "Evt_TopNonBJet1_Pt_Mu",    "p_{T}(leading non b-jet from hadronic t), #mu-ch. [GeV]",   "Events", output, 10,1 ); 
    drawStackWithData(f, "Evt_TopNonBJet1_E_El",     "Energy(leading non b-jet from hadronic t), e-ch. [GeV]",    "Events", output, 10,1 );  
    drawStackWithData(f, "Evt_TopNonBJet1_E_Mu",     "Energy(leading non b-jet from hadronic t), #mu-ch. [GeV]",  "Events", output, 10,1 ); 
    drawStackWithData(f, "Evt_TopNonBJet1_Eta_El",   "#eta(leading non b-jet from hadronic t), e-ch.",      "Events", output, 2 ,1 );  
    drawStackWithData(f, "Evt_TopNonBJet1_Eta_Mu",   "#eta(leading non b-jet from hadronic t), #mu-ch.",    "Events", output, 2 ,1 ); 
    drawStackWithData(f, "Evt_TopNonBJet2_Pt_El",    "p_{T}(second non b-jet from hadronic t), e-ch. [GeV]",      "Events", output, 10,1 );  
    drawStackWithData(f, "Evt_TopNonBJet2_Pt_Mu",    "p_{T}(second non b-jet from hadronic t), #mu-ch. [GeV]",    "Events", output, 10,1 ); 
    drawStackWithData(f, "Evt_TopNonBJet2_E_El",     "Energy(second non b-jet from hadronic t), e-ch. [GeV]",     "Events", output, 10,1 );  
    drawStackWithData(f, "Evt_TopNonBJet2_E_Mu",     "Energy(second non b-jet from hadronic t), #mu-ch. [GeV]",   "Events", output, 10,1 ); 
    drawStackWithData(f, "Evt_TopNonBJet2_Eta_El",   "#eta(second non b-jet from hadronic t), e-ch.",       "Events", output, 2 ,1 );  
    drawStackWithData(f, "Evt_TopNonBJet2_Eta_Mu",   "#eta(second non b-jet from hadronic t), #mu-ch.",     "Events", output, 2 ,1 ); 
    drawStackWithData(f, "Evt_bJet_Pt_El",           "p_{T}(b-jet), e-ch. [GeV]",                                 "Events", output, 10 ,1);  
    drawStackWithData(f, "Evt_bJet_Pt_Mu",           "p_{T}(b-jet), #mu-ch. [GeV]",                               "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_bJet_E_El",            "Energy(b-jet), e-ch. [GeV]",                                "Events", output, 10 ,1);  
    drawStackWithData(f, "Evt_bJet_E_Mu",            "Energy(b-jet), #mu-ch. [GeV]",                              "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_bJet_Eta_El",          "#eta(b-jet), e-ch.",                                  "Events", output, 2  ,1);  
    drawStackWithData(f, "Evt_bJet_Eta_Mu",          "#eta(b-jet), #mu-ch.",                                "Events", output, 2  ,1); 
    drawStackWithData(f, "Evt_bbarJet_Pt_El",        "p_{T}(#bar{b}-jet), e-ch. [GeV]",                           "Events", output, 10 ,1);  
    drawStackWithData(f, "Evt_bbarJet_Pt_Mu",        "p_{T}(#bar{b}-jet), #mu-ch. [GeV]",                         "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_bbarJet_E_El",         "Energy(#bar{b}-jet), e-ch. [GeV]",                          "Events", output, 10 ,1);  
    drawStackWithData(f, "Evt_bbarJet_E_Mu",         "Energy(#bar{b}-jet), #mu-ch. [GeV]",                        "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_bbarJet_Eta_El",       "#eta(#bar{b}-jet), e-ch.",                            "Events", output, 2  ,1);  
    drawStackWithData(f, "Evt_bbarJet_Eta_Mu",       "#eta(#bar{b}-jet), #mu-ch.",                          "Events", output, 2  ,1); 
    drawStackWithData(f, "Evt_Top_Hadronic_Chi2_El", "#chi^{2}_{min}(jjb), e-ch.",                          "Events", output, 5  ,1);
    drawStackWithData(f, "Evt_Top_Hadronic_Chi2_Mu", "#chi^{2}_{min}(jjb), #mu-ch.",                        "Events", output, 5  ,1);
    drawStackWithData(f, "Evt_Top_Hadronic_Mass_El", "M_{jjb} [GeV]",                            "Events", output, 10 ,1);
    drawStackWithData(f, "Evt_Top_Hadronic_Mass_Mu", "M_{jjb} [GeV]",                          "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_Top_Hadronic_Eta_El",  "#eta_{top}(jjb), e-ch.",                              "Events", output, 2  ,1);
    drawStackWithData(f, "Evt_Top_Hadronic_Eta_Mu",  "#eta_{top}(jjb), #mu-ch.",                            "Events", output, 2  ,1);
    drawStackWithData(f, "Evt_Top_Hadronic_Pt_El",   "p_{T, top}(jjb), e-ch. [GeV]",                              "Events", output, 10 ,1);
    drawStackWithData(f, "Evt_Top_Hadronic_Pt_Mu",   "p_{T, top}(jjb), #mu-ch. [GeV]",                            "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_isoLep_Pt_Mu",         "p_{T}(isolated #mu) [GeV]",                                 "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_isoLep_Pt_El",         "p_{T}(isolated e) [GeV]",                                   "Events", output, 10 ,1); 
    drawStackWithData(f, "Evt_isoLep_Eta_Mu",        "#eta(isolated #mu)",                                  "Events", output, 2  ,1); 
    drawStackWithData(f, "Evt_isoLep_Eta_El",        "#eta(isolated e)",                                    "Events", output, 2  ,1);
    drawStackWithData(f, "Evt_Ht_El",                "H_{T}(selected jets), e-ch. [GeV]",                         "Events", output, 20 ,1 );  
    drawStackWithData(f, "Evt_Ht_Mu",                "H_{T}(selected jets), #mu-ch. [GeV]",                       "Events", output, 20 ,1 ); 
    drawStackWithData(f, "Evt_Top_Leptonic_Mbl_El",  "M_{eb} [GeV]",                                              "Events", output, 10 , 1);
    drawStackWithData(f, "Evt_Top_Leptonic_Mbl_Mu",  "M_{#mub} [GeV]",                                            "Events", output, 10 , 1); 
    // Linear chi2
    drawStackWithData(f, "EvtChi2_NSelJets_El",          "N(selected jets), e-ch.",                         "Events", output, 1 );  
    drawStackWithData(f, "EvtChi2_NSelJets_Mu",          "N(selected jets), #mu-ch.",                       "Events", output, 1 );  
    drawStackWithData(f, "EvtChi2_NBJets_El",            "N(CSVM b-tagged jets), e-ch.",                    "Events", output, 1 );  
    drawStackWithData(f, "EvtChi2_NBJets_Mu",            "N(CSVM b-tagged jets), #mu-ch.",                  "Events", output, 1 );  
    drawStackWithData(f, "EvtChi2_HardJet_Pt_El",        "p_{T}(leading jet), e-ch. [GeV]",                       "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_HardJet_Pt_Mu",        "p_{T}(leading jet), #mu-ch. [GeV]",                     "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_HardJet_E_El",         "Energy(leading jet), e-ch. [GeV]",                      "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_HardJet_E_Mu",         "Energy(leading jet), #mu-ch. [GeV]",                    "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_HardJet_Eta_El",       "#eta(leading jet), e-ch.",                        "Events", output, 2  );  
    drawStackWithData(f, "EvtChi2_HardJet_Eta_Mu",       "#eta(leading jet), #mu-ch.",                      "Events", output, 2  ); 
    drawStackWithData(f, "EvtChi2_HardNonBJet1_Pt_El",   "p_{T}(leading non b-jet), e-ch. [GeV]",                 "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_HardNonBJet1_Pt_Mu",   "p_{T}(leading non b-jet), #mu-ch. [GeV]",               "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_HardNonBJet1_E_El",    "Energy(leading non b-jet), e-ch.",                "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_HardNonBJet1_E_Mu",    "Energy(leading non b-jet), #mu-ch. [GeV]",              "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_HardNonBJet1_Eta_El",  "#eta(leading non b-jet), e-ch.",                  "Events", output, 2  );  
    drawStackWithData(f, "EvtChi2_HardNonBJet1_Eta_Mu",  "#eta(leading non b-jet), #mu-ch.",                "Events", output, 2  ); 
    drawStackWithData(f, "EvtChi2_HardNonBJet2_Pt_El",   "p_{T}(second non b-jet), e-ch. [GeV]",                  "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_HardNonBJet2_Pt_Mu",   "p_{T}(second non b-jet), #mu-ch. [GeV]",                "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_HardNonBJet2_E_El",    "Energy(second non b-jet), e-ch. [GeV]",                 "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_HardNonBJet2_E_Mu",    "Energy(second non b-jet), #mu-ch. [GeV]",               "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_HardNonBJet2_Eta_El",  "#eta(second non b-jet), e-ch.",                   "Events", output, 2  );  
    drawStackWithData(f, "EvtChi2_HardNonBJet2_Eta_Mu",  "#eta(second non b-jet), #mu-ch.",                 "Events", output, 2  ); 
    drawStackWithData(f, "EvtChi2_TopNonBJet1_Pt_El",    "p_{T}(leading non b-jet from hadronic t), e-ch. [GeV]",     "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_TopNonBJet1_Pt_Mu",    "p_{T}(leading non b-jet from hadronic t), #mu-ch. [GeV]",   "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_TopNonBJet1_E_El",     "Energy(leading non b-jet from hadronic t), e-ch. [GeV]",    "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_TopNonBJet1_E_Mu",     "Energy(leading non b-jet from hadronic t), #mu-ch. [GeV]",  "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_TopNonBJet1_Eta_El",   "#eta(leading non b-jet from hadronic t), e-ch.",      "Events", output, 2  );  
    drawStackWithData(f, "EvtChi2_TopNonBJet1_Eta_Mu",   "#eta(leading non b-jet from hadronic t), #mu-ch.",    "Events", output, 2  ); 
    drawStackWithData(f, "EvtChi2_TopNonBJet2_Pt_El",    "p_{T}(second non b-jet from hadronic t), e-ch. [GeV]",   "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_TopNonBJet2_Pt_Mu",    "p_{T}(second non b-jet from hadronic t), #mu-ch. [GeV]", "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_TopNonBJet2_E_El",     "Energy(second non b-jet from hadronic t), e-ch. [GeV]",  "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_TopNonBJet2_E_Mu",     "Energy(second non b-jet from hadronic t), #mu-ch. [GeV]","Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_TopNonBJet2_Eta_El",   "#eta(second non b-jet from hadronic t), e-ch.",    "Events", output, 2  );  
    drawStackWithData(f, "EvtChi2_TopNonBJet2_Eta_Mu",   "#eta(second non b-jet from hadronic t), #mu-ch.",  "Events", output, 2  ); 
    drawStackWithData(f, "EvtChi2_bJet_Pt_El",           "p_{T}(b-jet), e-ch. [GeV]",                              "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_bJet_Pt_Mu",           "p_{T}(b-jet), #mu-ch. [GeV]",                            "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_bJet_E_El",            "Energy(b-jet), e-ch. [GeV]",                             "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_bJet_E_Mu",            "Energy(b-jet), #mu-ch. [GeV]",                           "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_bJet_Eta_El",          "#eta(b-jet), e-ch.",                               "Events", output, 2  );  
    drawStackWithData(f, "EvtChi2_bJet_Eta_Mu",          "#eta(b-jet), #mu-ch.",                             "Events", output, 2  ); 
    drawStackWithData(f, "EvtChi2_bbarJet_Pt_El",        "p_{T}(#bar{b}-jet), e-ch. [GeV]",                        "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_bbarJet_Pt_Mu",        "p_{T}(#bar{b}-jet), #mu-ch. [GeV]",                      "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_bbarJet_E_El",         "Energy(#bar{b}-jet), e-ch. [GeV]",                       "Events", output, 10 );  
    drawStackWithData(f, "EvtChi2_bbarJet_E_Mu",         "Energy(#bar{b}-jet), #mu-ch. [GeV]",                     "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_bbarJet_Eta_El",       "#eta(#bar{b}-jet), e-ch.",                         "Events", output, 2  );  
    drawStackWithData(f, "EvtChi2_bbarJet_Eta_Mu",       "#eta(#bar{b}-jet), #mu-ch.",                       "Events", output, 2  ); 
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Mass_El", "M_{jjb} [GeV]",                         "Events / 10 GeV", output, 10, 0, 0, 0, 0, 0, 1, 1, "1 e, #geq 4 jets (2 b-jets)"  );
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Mass_Mu", "M_{jjb} [GeV]",                         "Events / 10 GeV", output, 10, 0, 0, 0, 0, 0, 1, 1, "1 #mu, #geq 4 jets (2 b-jets)"  ); 
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Chi2_El", "#chi^{2}_{min}(jjb)",                       "Events", output, 5, 0, 0, 0, 0, 0, 0, 1, "1 e, #geq 4 jets (2 b-jets)" );
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Chi2_Mu", "#chi^{2}_{min}(jjb)",                       "Events", output, 5, 0, 0, 0, 0, 0, 0, 1, "1 #mu, #geq 4 jets (2 b-jets)" );
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Eta_El",  "#eta_{top}(jjb), e-ch.",                           "Events", output, 2  );
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Eta_Mu",  "#eta_{top}(jjb), #mu-ch.",                         "Events", output, 2  );
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Pt_El",   "p_{T, top}(jjb), e-ch. [GeV]",                           "Events", output, 10 );
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Pt_Mu",   "p_{T, top}(jjb), #mu-ch. [GeV]",                         "Events", output, 10 ); 
    drawStackWithData(f, "EvtChi2_isoLep_Pt_Mu",         "p_{T}(isolated #mu) [GeV]",                           "Events", output, 10, 0, 0, 0, 0, 0, 0, 1, "1 e, #geq 4 jets (2 b-jets)"  ); 
    drawStackWithData(f, "EvtChi2_isoLep_Pt_El",         "p_{T}(isolated e) [GeV]",                             "Events", output, 10, 0, 0, 0, 0, 0, 0, 1, "1 #mu, #geq 4 jets (2 b-jets)"  ); 
    drawStackWithData(f, "EvtChi2_isoLep_Eta_Mu",        "#eta(isolated #mu)",                            "Events", output, 2  ); 
    drawStackWithData(f, "EvtChi2_isoLep_Eta_El",        "#eta(isolated e)",                              "Events", output, 2  );
    drawStackWithData(f, "EvtChi2_Ht_El",                "H_{T}(selected jets), e-ch. [GeV]",                   "Events", output, 20, 0, 0, 0, 0, 0, 0, 1, "1 e, #geq 4 jets (2 b-jets)"  );  
    drawStackWithData(f, "EvtChi2_Ht_Mu",                "H_{T}(selected jets), #mu-ch. [GeV]",                 "Events", output, 20, 0, 0, 0, 0, 0, 0, 1, "1 #mu, #geq 4 jets (2 b-jets)"  ); 
    drawStackWithData(f, "EvtChi2_Top_Leptonic_Mbl_El",  "M_{eb} [GeV]",                                              "Events / 10 GeV", output, 10,  0, 0, 0, 0, 0, 2, 1, "1 e, #geq 4 jets (2 b-jets)" );
    drawStackWithData(f, "EvtChi2_Top_Leptonic_Mbl_Mu",  "M_{#mub} [GeV]",                                            "Events / 10 GeV", output, 10,  0, 0, 0, 0, 0, 3, 1, "1 #mu, #geq 4 jets (2 b-jets)" ); 
    // Log
    drawStackWithData(f, "EvtChi2_NSelJets_El",          "N(selected jets), e-ch.",                                    "Events", output, 1  ,1);  
    drawStackWithData(f, "EvtChi2_NSelJets_Mu",          "N(selected jets), #mu-ch.",                                  "Events", output, 1  ,1);  
    drawStackWithData(f, "EvtChi2_NBJets_El",            "N(CSVM b-tagged jets), e-ch.",                               "Events", output, 1  ,1);  
    drawStackWithData(f, "EvtChi2_NBJets_Mu",            "N(CSVM b-tagged jets), #mu-ch.",                             "Events", output, 1  ,1);  
    drawStackWithData(f, "EvtChi2_HardJet_Pt_El",        "p_{T}(leading jet), e-ch. [GeV]",                            "Events", output, 10 ,1);  
    drawStackWithData(f, "EvtChi2_HardJet_Pt_Mu",        "p_{T}(leading jet), #mu-ch. [GeV]",                          "Events", output, 10 ,1); 
    drawStackWithData(f, "EvtChi2_HardJet_E_El",         "Energy(leading jet), e-ch. [GeV]",                           "Events", output, 10 ,1);  
    drawStackWithData(f, "EvtChi2_HardJet_E_Mu",         "Energy(leading jet), #mu-ch. [GeV]",                         "Events", output, 10 ,1); 
    drawStackWithData(f, "EvtChi2_HardJet_Eta_El",       "#eta(leading jet), e-ch.",                                   "Events", output, 2  ,1);  
    drawStackWithData(f, "EvtChi2_HardJet_Eta_Mu",       "#eta(leading jet), #mu-ch.",                                 "Events", output, 2  ,1); 
    drawStackWithData(f, "EvtChi2_HardNonBJet1_Pt_El",    "p_{T}(leading non b-jet), e-ch. [GeV]",                     "Events", output, 10 ,1);  
    drawStackWithData(f, "EvtChi2_HardNonBJet1_Pt_Mu",    "p_{T}(leading non b-jet), #mu-ch. [GeV]",                   "Events", output, 10 ,1); 
    drawStackWithData(f, "EvtChi2_HardNonBJet1_E_El",     "Energy(leading non b-jet), e-ch. [GeV]",                    "Events", output, 10 ,1);  
    drawStackWithData(f, "EvtChi2_HardNonBJet1_E_Mu",     "Energy(leading non b-jet), #mu-ch. [GeV]",                  "Events", output, 10 ,1); 
    drawStackWithData(f, "EvtChi2_HardNonBJet1_Eta_El",   "#eta(leading b-jet), e-ch.",                                "Events", output, 2  ,1);  
    drawStackWithData(f, "EvtChi2_HardNonBJet1_Eta_Mu",   "#eta(leading b-jet), #mu-ch.",                              "Events", output, 2  ,1); 
    drawStackWithData(f, "EvtChi2_HardNonBJet2_Pt_El",   "p_{T}(second non b-jet), e-ch. [GeV]",                       "Events", output, 10 ,1);  
    drawStackWithData(f, "EvtChi2_HardNonBJet2_Pt_Mu",   "p_{T}(second non b-jet), #mu-ch. [GeV]",                     "Events", output, 10 ,1); 
    drawStackWithData(f, "EvtChi2_HardNonBJet2_E_El",    "Energy(second non b-jet), e-ch. [GeV]",                      "Events", output, 10 ,1);  
    drawStackWithData(f, "EvtChi2_HardNonBJet2_E_Mu",    "Energy(second non b-jet), #mu-ch. [GeV]",                    "Events", output, 10 ,1); 
    drawStackWithData(f, "EvtChi2_HardNonBJet2_Eta_El",  "#eta(second non b-jet), e-ch.",                              "Events", output, 2  ,1);  
    drawStackWithData(f, "EvtChi2_HardNonBJet2_Eta_Mu",  "#eta(second non b-jet), #mu-ch.",                            "Events", output, 2  ,1); 
    drawStackWithData(f, "EvtChi2_TopNonBJet1_Pt_El",    "p_{T}(leading non b-jet from hadronic t), e-ch. [GeV]",      "Events", output, 10,1 );  
    drawStackWithData(f, "EvtChi2_TopNonBJet1_Pt_Mu",    "p_{T}(leading non b-jet from hadronic t), #mu-ch. [GeV]",    "Events", output, 10,1 ); 
    drawStackWithData(f, "EvtChi2_TopNonBJet1_E_El",     "Energy(leading non b-jet from hadronic t), e-ch. [GeV]",     "Events", output, 10,1 );  
    drawStackWithData(f, "EvtChi2_TopNonBJet1_E_Mu",     "Energy(leading non b-jet from hadronic t), #mu-ch. [GeV]",   "Events", output, 10,1 ); 
    drawStackWithData(f, "EvtChi2_TopNonBJet1_Eta_El",   "#eta(leading non b-jet from hadronic t), e-ch.",             "Events", output, 2 ,1 );  
    drawStackWithData(f, "EvtChi2_TopNonBJet1_Eta_Mu",   "#eta(leading non b-jet from hadronic t), #mu-ch.",           "Events", output, 2 ,1 ); 
    drawStackWithData(f, "EvtChi2_TopNonBJet2_Pt_El",    "p_{T}(second non b-jet from hadronic t), e-ch. [GeV]",       "Events", output, 10,1 );  
    drawStackWithData(f, "EvtChi2_TopNonBJet2_Pt_Mu",    "p_{T}(second non b-jet from hadronic t), #mu-ch. [GeV]",     "Events", output, 10,1 ); 
    drawStackWithData(f, "EvtChi2_TopNonBJet2_E_El",     "Energy(second non b-jet from hadronic t), e-ch. [GeV]",      "Events", output, 10,1 );  
    drawStackWithData(f, "EvtChi2_TopNonBJet2_E_Mu",     "Energy(second non b-jet from hadronic t), #mu-ch. [GeV]",    "Events", output, 10,1 ); 
    drawStackWithData(f, "EvtChi2_TopNonBJet2_Eta_El",   "#eta(second non b-jet from hadronic t), e-ch.",              "Events", output, 2 ,1 );  
    drawStackWithData(f, "EvtChi2_TopNonBJet2_Eta_Mu",   "#eta(second non b-jet from hadronic t), #mu-ch.",            "Events", output, 2 ,1 ); 
    drawStackWithData(f, "EvtChi2_bJet_Pt_El",           "p_{T}(b-jet), e-ch. [GeV]",                                  "Events", output, 10 ,1);  
    drawStackWithData(f, "EvtChi2_bJet_Pt_Mu",           "p_{T}(b-jet), #mu-ch. [GeV]",                                "Events", output, 10 ,1); 
    drawStackWithData(f, "EvtChi2_bJet_E_El",            "Energy(b-jet), e-ch. [GeV]",                                 "Events", output, 10 ,1);  
    drawStackWithData(f, "EvtChi2_bJet_E_Mu",            "Energy(b-jet), #mu-ch. [GeV]",                               "Events", output, 10 ,1); 
    drawStackWithData(f, "EvtChi2_bJet_Eta_El",          "#eta(b-jet), e-ch.",                                         "Events", output, 2  ,1);  
    drawStackWithData(f, "EvtChi2_bJet_Eta_Mu",          "#eta(b-jet), #mu-ch.",                                       "Events", output, 2  ,1); 
    drawStackWithData(f, "EvtChi2_bbarJet_Pt_El",        "p_{T}(#bar{b}-jet), e-ch. [GeV]",                            "Events", output, 10 ,1);  
    drawStackWithData(f, "EvtChi2_bbarJet_Pt_Mu",        "p_{T}(#bar{b}-jet), #mu-ch. [GeV]",                          "Events", output, 10 ,1); 
    drawStackWithData(f, "EvtChi2_bbarJet_E_El",         "Energy(#bar{b}-jet), e-ch. [GeV]",                           "Events", output, 10 ,1);  
    drawStackWithData(f, "EvtChi2_bbarJet_E_Mu",         "Energy(#bar{b}-jet), #mu-ch. [GeV]",                         "Events", output, 10 ,1); 
    drawStackWithData(f, "EvtChi2_bbarJet_Eta_El",       "#eta(#bar{b}-jet), e-ch.",                                   "Events", output, 2  ,1);  
    drawStackWithData(f, "EvtChi2_bbarJet_Eta_Mu",       "#eta(#bar{b}-jet), #mu-ch.",                                 "Events", output, 2  ,1); 
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Chi2_El", "#chi^{2}_{min}(jjb)",                               "Events", output, 5  ,1, 0, 0, 0, 0, 0, 1, "1 e, #geq 4 jets (2 b-jets)" );
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Chi2_Mu", "#chi^{2}_{min}(jjb)",                               "Events", output, 5  ,1, 0, 0, 0, 0, 0, 1, "1 #mu, #geq 4 jets (2 b-jets)" );
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Mass_El", "M_{jjb} [GeV]",                             "Events / 10 GeV", output, 10 ,1, 0, 0, 0, 0, 1, 1, "1 e, #geq 4 jets (2 b-jets)" );
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Mass_Mu", "M_{jjb} [GeV]",                             "Events / 10 GeV", output, 10 ,1, 0, 0, 0, 0, 1, 1, "1 #mu, #geq 4 jets (2 b-jets)" ); 
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Eta_El",  "#eta_{top}(jjb), e-ch. [GeV]",                               "Events", output, 2  ,1);
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Eta_Mu",  "#eta_{top}(jjb), #mu-ch.",                                   "Events", output, 2  ,1);
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Pt_El",   "p_{T, top}(jjb), e-ch. [GeV]",                               "Events", output, 10 ,1);
    drawStackWithData(f, "EvtChi2_Top_Hadronic_Pt_Mu",   "p_{T, top}(jjb), #mu-ch. [GeV]",                             "Events", output, 10 ,1); 
    drawStackWithData(f, "EvtChi2_isoLep_Pt_Mu",         "p_{T}(isolated #mu) [GeV]",                                        "Events", output, 10 ,1, 0, 0, 0, 0, 0, 1, "1 #mu, #geq 4 jets (2 b-jets)" ); 
    drawStackWithData(f, "EvtChi2_isoLep_Pt_El",         "p_{T}(isolated e) [GeV]",                                          "Events", output, 10 ,1, 0, 0, 0, 0, 0, 1, "1 e, #geq 4 jets (2 b-jets)" ); 
    drawStackWithData(f, "EvtChi2_isoLep_Eta_Mu",        "#eta(isolated #mu)",                                         "Events", output, 2  ,1); 
    drawStackWithData(f, "EvtChi2_isoLep_Eta_El",        "#eta(isolated e)",                                "Events", output, 2  ,1);
    drawStackWithData(f, "EvtChi2_Ht_El",                "H_{T}(selected jets), e-ch. [GeV]",                     "Events", output, 20 ,1 );  
    drawStackWithData(f, "EvtChi2_Ht_Mu",                "H_{T}(selected jets), #mu-ch. [GeV]",                   "Events", output, 20 ,1 );
    drawStackWithData(f, "EvtChi2_Top_Leptonic_Mbl_El",  "M_{eb} [GeV]",                                              "Events / 10 GeV", output, 10, 1, 0, 0, 0, 0, 2, 1, "1 e, #geq 4 jets (2 b-jets)" );
    drawStackWithData(f, "EvtChi2_Top_Leptonic_Mbl_Mu",  "M_{#mub} [GeV]",                                            "Events / 10 GeV", output, 10, 1, 0, 0, 0, 0, 3, 1, "1 #mu, #geq 4 jets (2 b-jets)" ); 

    drawStackWithData( f, "Evt_CutFlow_Mu", "", "Events", output, 1, true );
    drawStackWithData( f, "Evt_CutFlow_El", "", "Events", output, 1, true );
    drawStackWithData( f, "Evt_CutFlow_Mu", "", "Events", output, 1, false );
    drawStackWithData( f, "Evt_CutFlow_El", "", "Events", output, 1, false );

    draw2D(f, "TTJets_SemiLeptMGDecays__TH2_Chi2_vs_MET_El",            "", output, "#chi^{2}_{min}", "MET",                         5, 10, 2000   );
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2_Chi2_vs_MET_Mu",            "", output, "#chi^{2}_{min}", "MET",                       5, 10, 2000   );
    draw2D(f, "TTJets__TH2_Chi2_vs_MET_El",                             "", output, "#chi^{2}_{min}", "MET",                         5, 10, 2000   );
    draw2D(f, "TTJets__TH2_Chi2_vs_MET_Mu",                             "", output, "#chi^{2}_{min}", "MET",                       5, 10, 2000   );
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2_Chi2_vs_TopLeptonicMbl_El",            "", output, "#chi^{2}_{min}", "Inv. M_{eb}",                         5, 10, 2000   );
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2_Chi2_vs_TopLeptonicMbl_Mu",            "", output, "#chi^{2}_{min}", "Inv. M_{#mub}",                       5, 10, 2000   );
    draw2D(f, "TTJets__TH2_Chi2_vs_TopLeptonicMbl_El",            "", output, "#chi^{2}_{min}", "Inv. M_{eb}",                         5, 10, 2000   );
    draw2D(f, "TTJets__TH2_Chi2_vs_TopLeptonicMbl_Mu",            "", output, "#chi^{2}_{min}", "Inv. M_{#mub}",                       5, 10, 2000   );
    draw2D(f, "MC__TH2_Chi2_vs_MET_El",                           "", output, "#chi^{2}_{min}", "MET",                         5, 10, 2000   );
    draw2D(f, "MC__TH2_Chi2_vs_MET_Mu",                           "", output, "#chi^{2}_{min}", "MET",                       5, 10, 2000   );
    draw2D(f, "DATA_Electron__TH2_Chi2_vs_MET_El",                "", output, "#chi^{2}_{min}", "MET",                         5, 10, 2000, 1);
    draw2D(f, "DATA_Muon__TH2_Chi2_vs_MET_Mu",                    "", output, "#chi^{2}_{min}", "MET",                       5, 10, 2000, 1);
    draw2D(f, "MC__TH2_Chi2_vs_TopLeptonicMbl_El",            "", output, "#chi^{2}_{min}", "Inv. M_{eb}",                         5, 10, 2000   );
    draw2D(f, "MC__TH2_Chi2_vs_TopLeptonicMbl_Mu",            "", output, "#chi^{2}_{min}", "Inv. M_{#mub}",                       5, 10, 2000   );
    draw2D(f, "DATA_Electron__TH2_Chi2_vs_TopLeptonicMbl_El", "", output, "#chi^{2}_{min}", "Inv. M_{eb}",                         5, 10, 2000, 1);
    draw2D(f, "DATA_Muon__TH2_Chi2_vs_TopLeptonicMbl_Mu",     "", output, "#chi^{2}_{min}", "Inv. M_{#mub}",                       5, 10, 2000, 1);
    draw2D(f, "MC__TH2_Chi2_vs_TopHadronicMass_El",            "", output, "#chi^{2}_{min}", "M_{jjb}",                         5, 10, 5500   );
    draw2D(f, "MC__TH2_Chi2_vs_TopHadronicMass_Mu",            "", output, "#chi^{2}_{min}", "M_{jjb}",                       5, 10, 5500   );
    draw2D(f, "DATA_Electron__TH2_Chi2_vs_TopHadronicMass_El", "", output, "#chi^{2}_{min}", "M_{jjb}",                         5, 10, 5500, 1);
    draw2D(f, "DATA_Muon__TH2_Chi2_vs_TopHadronicMass_Mu",     "", output, "#chi^{2}_{min}", "M_{jjb}",                       5, 10, 5500, 1);
    draw2D(f, "MC__TH2_Chi2_vs_Ht_El",                         "", output, "#chi^{2}_{min}", "H_{T}(selected jets), e-ch.",                      5, 20, 1900   );
    draw2D(f, "MC__TH2_Chi2_vs_Ht_Mu",                         "", output, "#chi^{2}_{min}", "H_{T}(selected jets), #mu-ch.",                    5, 20, 1900   );
    draw2D(f, "DATA_Electron__TH2_Chi2_vs_Ht_El",              "", output, "#chi^{2}_{min}", "H_{T}(selected jets), e-ch.",                      5, 20, 1900, 1);
    draw2D(f, "DATA_Muon__TH2_Chi2_vs_Ht_Mu",                  "", output, "#chi^{2}_{min}", "H_{T}(selected jets), #mu-ch.",                    5, 20, 1900, 1);
    draw2D(f, "MC__TH2_TopHadronicMass_vs_Ht_El",              "", output, "M_{jjb}",   "H_{T}(selected jets), e-ch.",   10, 20, 800 );
    draw2D(f, "MC__TH2_TopHadronicMass_vs_Ht_Mu",              "", output, "M_{jjb}", "H_{T}(selected jets), #mu-ch.", 10, 20, 800 );
    draw2D(f, "DATA_Electron__TH2_TopHadronicMass_vs_Ht_El",   "", output, "M_{jjb}",   "H_{T}(selected jets), e-ch.",   10, 20, 800, 1);
    draw2D(f, "DATA_Muon__TH2_TopHadronicMass_vs_Ht_Mu",       "", output, "M_{jjb}", "H_{T}(selected jets), #mu-ch.", 10, 20, 800, 1);
    draw2D(f, "MC__TH2_TopHadronicMass_vs_TopLeptonicMbl_El",              "", output, "M_{jjb}",   "Inv. M_{eb}",   10, 10, 700 );
    draw2D(f, "MC__TH2_TopHadronicMass_vs_TopLeptonicMbl_Mu",              "", output, "M_{jjb}", "Inv. M_{#mub}", 10, 10, 700 );
    draw2D(f, "DATA_Electron__TH2_TopHadronicMass_vs_TopLeptonicMbl_El",   "", output, "M_{jjb}",   "Inv. M_{eb}",   10, 10, 700, 1);
    draw2D(f, "DATA_Muon__TH2_TopHadronicMass_vs_TopLeptonicMbl_Mu",       "", output, "M_{jjb}", "Inv. M_{#mub}", 10, 10, 700,  1);
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2_TopHadronicMass_vs_TopLeptonicMbl_El",              "", output, "M_{jjb}",   "Inv. M_{eb}",   10, 10, 700 );
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2_TopHadronicMass_vs_TopLeptonicMbl_Mu",              "", output, "M_{jjb}", "Inv. M_{#mub}", 10, 10, 700 );
    draw2D(f, "TTJets__TH2_TopHadronicMass_vs_TopLeptonicMbl_El",              "", output, "M_{jjb}",   "Inv. M_{eb}",   10, 10, 700 );
    draw2D(f, "TTJets__TH2_TopHadronicMass_vs_TopLeptonicMbl_Mu",              "", output, "M_{jjb}", "Inv. M_{#mub}", 10, 10, 700 );
    draw2D(f, "MC__TH2_TopLeptonicMbl_vs_MET_El",              "", output,  "Inv. M_{eb}",   "MET", 10, 10, 500 );
    draw2D(f, "MC__TH2_TopLeptonicMbl_vs_MET_Mu",              "", output,  "Inv. M_{#mub}", "MET", 10, 10, 500 );
    draw2D(f, "DATA_Electron__TH2_TopLeptonicMbl_vs_MET_El",   "", output,  "Inv. M_{eb}",   "MET", 10, 10, 500, 1);
    draw2D(f, "DATA_Muon__TH2_TopLeptonicMbl_vs_MET_Mu",       "", output,  "Inv. M_{#mub}", "MET", 10, 10, 500,  1);
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2_TopLeptonicMbl_vs_MET_El",              "", output, "Inv. M_{eb}",   "MET", 10, 10, 500 );
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2_TopLeptonicMbl_vs_MET_Mu",              "", output, "Inv. M_{#mub}", "MET", 10, 10, 500 );
    draw2D(f, "TTJets__TH2_TopLeptonicMbl_vs_MET_El",                               "", output, "Inv. M_{eb}",   "MET", 10, 10, 500 );
    draw2D(f, "TTJets__TH2_TopLeptonicMbl_vs_MET_Mu",                               "", output, "Inv. M_{#mub}", "MET", 10, 10, 500 );

    draw2D(f, "TTJets_SemiLeptMGDecays__TH2Chi2_Chi2_vs_MET_El",            "", output, "#chi^{2}_{min}", "MET",                         5, 10, 2000   );
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2Chi2_Chi2_vs_MET_Mu",            "", output, "#chi^{2}_{min}", "MET",                       5, 10, 2000   );
    draw2D(f, "TTJets__TH2Chi2_Chi2_vs_MET_El",                             "", output, "#chi^{2}_{min}", "MET",                         5, 10, 2000   );
    draw2D(f, "TTJets__TH2Chi2_Chi2_vs_MET_Mu",                             "", output, "#chi^{2}_{min}", "MET",                       5, 10, 2000   );
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2Chi2_Chi2_vs_TopLeptonicMbl_El",            "", output, "#chi^{2}_{min}", "Inv. M_{eb}, e-ch.",                         5, 10, 2000   );
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2Chi2_Chi2_vs_TopLeptonicMbl_Mu",            "", output, "#chi^{2}_{min}", "Inv. M_{#mub}, #mu-ch.",                       5, 10, 2000   );
    draw2D(f, "TTJets__TH2Chi2_Chi2_vs_TopLeptonicMbl_El",            "", output, "#chi^{2}_{min}", "Inv. M_{eb}, e-ch.",                         5, 10, 2000   );
    draw2D(f, "TTJets__TH2Chi2_Chi2_vs_TopLeptonicMbl_Mu",            "", output, "#chi^{2}_{min}", "Inv. M_{#mub}, #mu-ch.",                       5, 10, 2000   );
    draw2D(f, "MC__TH2Chi2_Chi2_vs_MET_El",                           "", output, "#chi^{2}_{min}", "MET",                         5, 10, 2000   );
    draw2D(f, "MC__TH2Chi2_Chi2_vs_MET_Mu",                           "", output, "#chi^{2}_{min}", "MET",                       5, 10, 2000   );
    draw2D(f, "DATA_Electron__TH2Chi2_Chi2_vs_MET_El",                "", output, "#chi^{2}_{min}", "MET",                         5, 10, 2000, 1);
    draw2D(f, "DATA_Muon__TH2Chi2_Chi2_vs_MET_Mu",                    "", output, "#chi^{2}_{min}", "MET",                       5, 10, 2000, 1);
    draw2D(f, "MC__TH2Chi2_Chi2_vs_TopLeptonicMbl_El",            "", output, "#chi^{2}_{min}", "Inv. M_{eb}, e-ch.",                         5, 10, 2000   );
    draw2D(f, "MC__TH2Chi2_Chi2_vs_TopLeptonicMbl_Mu",            "", output, "#chi^{2}_{min}", "Inv. M_{#mub}, #mu-ch.",                       5, 10, 2000   );
    draw2D(f, "DATA_Electron__TH2Chi2_Chi2_vs_TopLeptonicMbl_El", "", output, "#chi^{2}_{min}", "Inv. M_{eb}, e-ch.",                         5, 10, 2000, 1);
    draw2D(f, "DATA_Muon__TH2Chi2_Chi2_vs_TopLeptonicMbl_Mu",     "", output, "#chi^{2}_{min}", "Inv. M_{#mub}, #mu-ch.",                       5, 10, 2000, 1);
    draw2D(f, "MC__TH2Chi2_Chi2_vs_TopHadronicMass_El",            "", output, "#chi^{2}_{min}", "M_{jjb}",                         5, 10, 2000   );
    draw2D(f, "MC__TH2Chi2_Chi2_vs_TopHadronicMass_Mu",            "", output, "#chi^{2}_{min}", "M_{jjb}",                       5, 10, 2000   );
    draw2D(f, "DATA_Electron__TH2Chi2_Chi2_vs_TopHadronicMass_El", "", output, "#chi^{2}_{min}", "M_{jjb}",                         5, 10, 2000, 1);
    draw2D(f, "DATA_Muon__TH2Chi2_Chi2_vs_TopHadronicMass_Mu",     "", output, "#chi^{2}_{min}", "M_{jjb}",                       5, 10, 2000, 1);
    draw2D(f, "MC__TH2Chi2_Chi2_vs_Ht_El",                         "", output, "#chi^{2}_{min}", "H_{T}(selected jets), e-ch.",                      5, 20,  900  );
    draw2D(f, "MC__TH2Chi2_Chi2_vs_Ht_Mu",                         "", output, "#chi^{2}_{min}", "H_{T}(selected jets), #mu-ch.",                    5, 20,  900  );
    draw2D(f, "DATA_Electron__TH2Chi2_Chi2_vs_Ht_El",              "", output, "#chi^{2}_{min}", "H_{T}(selected jets), e-ch.",                      5, 20, 900, 1);
    draw2D(f, "DATA_Muon__TH2Chi2_Chi2_vs_Ht_Mu",                  "", output, "#chi^{2}_{min}", "H_{T}(selected jets), #mu-ch.",                    5, 20, 900, 1);
    draw2D(f, "MC__TH2Chi2_TopHadronicMass_vs_Ht_El",              "", output, "M_{jjb}",   "H_{T}(selected jets), e-ch.",   10, 20, 300 );
    draw2D(f, "MC__TH2Chi2_TopHadronicMass_vs_Ht_Mu",              "", output, "M_{jjb}", "H_{T}(selected jets), #mu-ch.", 10, 20, 300 );
    draw2D(f, "DATA_Electron__TH2Chi2_TopHadronicMass_vs_Ht_El",   "", output, "M_{jjb}",   "H_{T}(selected jets), e-ch.",   10, 20, 300, 1);
    draw2D(f, "DATA_Muon__TH2Chi2_TopHadronicMass_vs_Ht_Mu",       "", output, "M_{jjb}", "H_{T}(selected jets), #mu-ch.", 10, 20, 300,  1);
    draw2D(f, "MC__TH2Chi2_TopHadronicMass_vs_TopLeptonicMbl_El",              "", output, "M_{jjb}",   "Inv. M_{eb}",   10, 10, 700 );
    draw2D(f, "MC__TH2Chi2_TopHadronicMass_vs_TopLeptonicMbl_Mu",              "", output, "M_{jjb}", "Inv. M_{#mub}", 10, 10, 700 );
    draw2D(f, "DATA_Electron__TH2Chi2_TopHadronicMass_vs_TopLeptonicMbl_El",   "", output, "M_{jjb}",   "Inv. M_{eb}",   10, 10, 700, 1);
    draw2D(f, "DATA_Muon__TH2Chi2_TopHadronicMass_vs_TopLeptonicMbl_Mu",       "", output, "M_{jjb}", "Inv. M_{#mub}", 10, 10, 700,  1);
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2Chi2_TopHadronicMass_vs_TopLeptonicMbl_El",              "", output, "M_{jjb}",   "Inv. M_{eb}",   10, 10, 700 );
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2Chi2_TopHadronicMass_vs_TopLeptonicMbl_Mu",              "", output, "M_{jjb}", "Inv. M_{#mub}", 10, 10, 700 );
    draw2D(f, "TTJets__TH2Chi2_TopHadronicMass_vs_TopLeptonicMbl_El",              "", output, "M_{jjb}",   "Inv. M_{eb}",   10, 10, 700 );
    draw2D(f, "TTJets__TH2Chi2_TopHadronicMass_vs_TopLeptonicMbl_Mu",              "", output, "M_{jjb}", "Inv. M_{#mub}", 10, 10, 700 );
    draw2D(f, "MC__TH2Chi2_TopLeptonicMbl_vs_MET_El",              "", output,  "Inv. M_{eb}",   "MET", 10, 10, 500 );
    draw2D(f, "MC__TH2Chi2_TopLeptonicMbl_vs_MET_Mu",              "", output,  "Inv. M_{#mub}", "MET", 10, 10, 500 );
    draw2D(f, "DATA_Electron__TH2Chi2_TopLeptonicMbl_vs_MET_El",   "", output,  "Inv. M_{eb}",   "MET", 10, 10, 500, 1);
    draw2D(f, "DATA_Muon__TH2Chi2_TopLeptonicMbl_vs_MET_Mu",       "", output,  "Inv. M_{#mub}", "MET", 10, 10, 500,  1);
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2Chi2_TopLeptonicMbl_vs_MET_El",              "", output, "Inv. M_{eb}",   "MET", 10, 10, 500 );
    draw2D(f, "TTJets_SemiLeptMGDecays__TH2Chi2_TopLeptonicMbl_vs_MET_Mu",              "", output, "Inv. M_{#mub}", "MET", 10, 10, 500 );
    draw2D(f, "TTJets__TH2Chi2_TopLeptonicMbl_vs_MET_El",                               "", output, "Inv. M_{eb}",   "MET", 10, 10, 500 );
    draw2D(f, "TTJets__TH2Chi2_TopLeptonicMbl_vs_MET_Mu",                               "", output, "Inv. M_{#mub}", "MET", 10, 10, 500 );

    //draw2D(f, "MC__TH2_Chi2_vs_TopHadronicMass_El",            "", output, "#chi^{2}_{min}", "M_{jjb}",                         5, 10, 2000   );
    //draw2D(f, "MC__TH2_Chi2_vs_TopHadronicMass_Mu",            "", output, "#chi^{2}_{min}", "M_{jjb}",                       5, 10, 2000   );
    //draw2D(f, "DATA_Electron__TH2_Chi2_vs_TopHadronicMass_El", "", output, "#chi^{2}_{min}", "M_{jjb}",                         5, 10, 2000, 1);
    //draw2D(f, "DATA_Muon__TH2_Chi2_vs_TopHadronicMass_Mu",     "", output, "#chi^{2}_{min}", "M_{jjb}",                       5, 10, 2000, 1);
    //draw2D(f, "MC__TH2_Chi2_vs_Ht_El",                         "", output, "#chi^{2}_{min}", "H_{T}(selected jets), e-ch.",                      5, 20,  900  );
    //draw2D(f, "MC__TH2_Chi2_vs_Ht_Mu",                         "", output, "#chi^{2}_{min}", "H_{T}(selected jets), #mu-ch.",                    5, 20,  900  );
    //draw2D(f, "DATA_Electron__TH2_Chi2_vs_Ht_El",              "", output, "#chi^{2}_{min}", "H_{T}(selected jets), e-ch.",                      5, 20, 900, 1);
    //draw2D(f, "DATA_Muon__TH2_Chi2_vs_Ht_Mu",                  "", output, "#chi^{2}_{min}", "H_{T}(selected jets), #mu-ch.",                    5, 20, 900, 1);
    //draw2D(f, "MC__TH2_TopHadronicMass_vs_Ht_El",              "", output, "M_{jjb}",   "H_{T}(selected jets), e-ch.",   10, 20, 300 );
    //draw2D(f, "MC__TH2_TopHadronicMass_vs_Ht_Mu",              "", output, "M_{jjb}", "H_{T}(selected jets), #mu-ch.", 10, 20, 300 );
    //draw2D(f, "DATA_Electron__TH2_TopHadronicMass_vs_Ht_El",   "", output, "M_{jjb}",   "H_{T}(selected jets), e-ch.",   10, 20, 300, 1);
    //draw2D(f, "DATA_Muon__TH2_TopHadronicMass_vs_Ht_Mu",       "", output, "M_{jjb}", "H_{T}(selected jets), #mu-ch.", 10, 20, 300,  1);

    getCutFlowNum( f, "DATA_Muon__Evt_CutFlow_Mu", true, output);
    getCutFlowNum( f, "DATA_Electron__Evt_CutFlow_El", true, output);
    getCutFlowNum( f, "MC__Evt_CutFlow_Mu", true, output);
    getCutFlowNum( f, "MC__Evt_CutFlow_El", true, output);
    getCutFlowNum( f, "BkgMC__Evt_CutFlow_Mu", true, output);
    getCutFlowNum( f, "BkgMC__Evt_CutFlow_El", true, output);
    getCutFlowNum( f, "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__Evt_CutFlow_Mu", true, output);
    getCutFlowNum( f, "BkgMC_TTJetsNonSemiLeptMGDecaysExcluded__Evt_CutFlow_El", true, output);
    getCutFlowNum( f, "TTJets_SemiLeptMGDecays__Evt_CutFlow_Mu",    true, output);
    getCutFlowNum( f, "TTJets_SemiLeptMGDecays__Evt_CutFlow_El",    true, output);
    getCutFlowNum( f, "TTJets_NonSemiLeptMGDecays__Evt_CutFlow_Mu", true, output);
    getCutFlowNum( f, "TTJets_NonSemiLeptMGDecays__Evt_CutFlow_El", true, output);
    getCutFlowNum( f, "TTJets__Evt_CutFlow_Mu", true, output);
    getCutFlowNum( f, "TTJets__Evt_CutFlow_El", true, output);
    getCutFlowNum( f, "SingleT__Evt_CutFlow_Mu",                    true, output);
    getCutFlowNum( f, "SingleT__Evt_CutFlow_El",                    true, output);
    getCutFlowNum( f, "DiBoson__Evt_CutFlow_Mu",                    true, output);
    getCutFlowNum( f, "DiBoson__Evt_CutFlow_El",                    true, output);
    getCutFlowNum( f, "WJetsToLNu__Evt_CutFlow_Mu",                 true, output);
    getCutFlowNum( f, "WJetsToLNu__Evt_CutFlow_El",                 true, output);
    getCutFlowNum( f, "DYJetsToLL__Evt_CutFlow_Mu",                 true, output);
    getCutFlowNum( f, "DYJetsToLL__Evt_CutFlow_El",                 true, output);
    getCutFlowNum( f, "TTJets_FullLeptMGDecays__Evt_CutFlow_Mu",                 true, output);
    getCutFlowNum( f, "TTJets_FullLeptMGDecays__Evt_CutFlow_El",                 true, output);
    getCutFlowNum( f, "TTJets_HadronicMGDecays__Evt_CutFlow_Mu",                 true, output);
    getCutFlowNum( f, "TTJets_HadronicMGDecays__Evt_CutFlow_El",                 true, output);
}
